use_frameworks!

platform :ios, '10.0'

target 'WatchdogRunLoopObserver_Example' do
  pod 'WatchdogRunLoopObserver', :path => '../'

  target 'WatchdogRunLoopObserver_Tests' do
    inherit! :search_paths

    
  end
end
